apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: {{ .Values.opSecret.JWT_SECRET.secretName }}
  namespace: {{ .Release.Namespace }}
spec:
  itemPath: "vaults/{{ .Values.opSecret.JWT_SECRET.vault }}/items/{{ .Values.opSecret.JWT_SECRET.item }}"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: {{ .Values.opSecret.EMAIL_USER.secretName }}
  namespace: {{ .Release.Namespace }}
spec:
  itemPath: "vaults/{{ .Values.opSecret.EMAIL_USER.vault }}/items/{{ .Values.opSecret.EMAIL_USER.item }}"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: {{ .Values.opSecret.EMAIL_PASS.secretName }}
  namespace: {{ .Release.Namespace }}
spec:
  itemPath: "vaults/{{ .Values.opSecret.EMAIL_PASS.vault }}/items/{{ .Values.opSecret.EMAIL_PASS.item }}"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: {{ .Values.opSecret.SESSION_SECRET.secretName }}
  namespace: {{ .Release.Namespace }}
spec:
  itemPath: "vaults/{{ .Values.opSecret.SESSION_SECRET.vault }}/items/{{ .Values.opSecret.SESSION_SECRET.item }}"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: {{ .Values.opSecret.NODE_ENV.secretName }}
  namespace: {{ .Release.Namespace }}
spec:
  itemPath: "vaults/{{ .Values.opSecret.NODE_ENV.vault }}/items/{{ .Values.opSecret.NODE_ENV.item }}"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: {{ .Values.opSecret.DATABASE_URL.secretName }}
  namespace: {{ .Release.Namespace }}
spec:
  itemPath: "vaults/{{ .Values.opSecret.DATABASE_URL.vault }}/items/{{ .Values.opSecret.DATABASE_URL.item }}"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: {{ .Values.opSecret.DATABASE_USER.secretName }}
  namespace: {{ .Release.Namespace }}
spec:
  itemPath: "vaults/{{ .Values.opSecret.DATABASE_USER.vault }}/items/{{ .Values.opSecret.DATABASE_USER.item }}"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: {{ .Values.opSecret.DATABASE_PASSWORD.secretName }}
  namespace: {{ .Release.Namespace }}
spec:
  itemPath: "vaults/{{ .Values.opSecret.DATABASE_PASSWORD.vault }}/items/{{ .Values.opSecret.DATABASE_PASSWORD.item }}"
